FROM ruby:3.4.4-slim

# Rails app lives here
WORKDIR /app

# Install OS deps
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      build-essential \
      libpq-dev \
      nodejs \
      libyaml-dev \
      && rm -rf /var/lib/apt/lists/*

# Install bundler
RUN gem install bundler

# Install gems (cache layer)
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy app
COPY . .

ENV RAILS_ENV=development
ENV RACK_ENV=development

# Dev entrypoint: clean server pid, setup DB
ENTRYPOINT ["./bin/docker-entrypoint"]
CMD ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]

EXPOSE 3000

